name: conservation_data_app

description: A Flutter app for conservation data collection (plants and animals) with local SQLite storage.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  sqflite_common_ffi_web: ^0.4.2+3
  path_provider: ^2.1.1
  path_provider_platform_interface: ^2.1.1
  provider: ^6.0.5
  image_picker: ^1.0.4
  intl: ^0.18.1

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/placeholder.png